box: anaxexp/alpine:3.7-2.0.1

build:
  box:
    id: python:3.6-alpine
    cmd: /bin/sh
  steps:
    - script:
      name: build
      code: |
        pip install mkdocs-material markdown-include pygments
        mkdocs build

release:
  box:
    id: nginx:alpine
    cmd: /bin/sh
  steps:
    - script:
      name: mv static files
      code: |
        rm -rf /usr/share/nginx/html/*
        mkdir -p /usr/share/nginx/html/stacks/php/docs
        mv $WERCKER_SOURCE_DIR/site/* /usr/share/nginx/html/stacks/php/docs
    - internal/docker-push:
      registry: https://registry.hub.docker.com/v2
      username: $DOCKER_USERNAME
      password: $DOCKER_PASSWORD
      repository: anaxexp/php-docs
      tag: latest, $WERCKER_GIT_BRANCH
      cmd: nginx -g 'daemon off;'

deploy:
  steps:
    - script:
      name: deployment
      code: |
        curl -sS \
                -H "Content-type: application/json" \
                -H "Authorization: token ${ANAXEXP_API_TOKEN}" \
                -X POST https://api.anaxexp.com/api/v2/bundles/deploy?org_id="${ANAXEXP_ORG_UUID}"\&service_image=anaxexp/php-docs:"${WERCKER_GIT_BRANCH}"\&cause="${WERCKER_GIT_COMMIT}"